-- schema.sql

-- Create DB
CREATE DATABASE IF NOT EXISTS esun_sys;
USE esun_sys;

-- Create SeatingChartTb 
CREATE TABLE IF NOT EXISTS SeatingChartTb (
    FLOOR_SEAT_SEQ INT AUTO_INCREMENT PRIMARY KEY,
    FLOOR_NO INT NOT NULL,
    SEAT_NO INT
);

-- Create EmployeeTb
CREATE TABLE IF NOT EXISTS EmployeeTb (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
	EID VARCHAR(5) NOT NULL,
    FLOOR_SEAT_SEQ INT
    );